name: Check Issues

on:
  issues:
    types: [opened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Check contains version code
      - if: contains(github.event.issue.body, 'Slimefun 版本') != true
        id: close
        name: Close Issue (template)
        uses: peter-evans/close-issue@v1
        with:
          comment: 由于你未按照反馈模板提交, 系统已自动关闭你的 Issue.
